In [1]:
X=[]
Z=[]
IMG_SIZE=150
AB_DIR = 'C:\\Users\\Tanishqa Mahendru\\Desktop\\proj\\lakData\\abrasion'
LAC_DIR = 'C:\\Users\\Tanishqa Mahendru\\Desktop\\proj\\lakData\\lacerated'
BU_DIR = 'C:\\Users\\Tanishqa Mahendru\\Desktop\\proj\\lakData\\burn'

In [2]:
from tqdm import tqdm
import os      
import cv2
import numpy as np

def assign_label(img,wtype):
    return wtype

def make_train_data(wtype,DIR):
    for img in tqdm(os.listdir(DIR)):
        label=assign_label(img,wtype)
        path = os.path.join(DIR,img)
        img = cv2.imread(path,cv2.IMREAD_COLOR)
        img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))
        
        X.append(np.array(img))
        Z.append(str(label))
        
make_train_data('Abrasion',AB_DIR)
make_train_data('Laceration',LAC_DIR)
make_train_data('Burn',BU_DIR)

100%|█████████████████████████████████████████| 47/47 [00:00<00:00, 758.02it/s]


In [3]:
from keras import backend as K
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam,SGD,Adagrad,Adadelta,RMSprop
from keras.utils import to_categorical

Using TensorFlow backend.


In [4]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
Y=le.fit_transform(Z)
Y=to_categorical(Y,3)
X=np.array(X)

Y.shape

X=np.array(X)

X.shape

In [5]:
X=X/255
X.shape

(146, 150, 150, 3)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [7]:
from keras.layers import Dropout, Flatten,Activation
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

model = Sequential()
model.add(Conv2D(filters = 32, kernel_size = (5,5),padding = 'Same',activation ='relu', input_shape = (150,150,3)))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same',activation ='relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
 

model.add(Conv2D(filters =96, kernel_size = (3,3),padding = 'Same',activation ='relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))

model.add(Conv2D(filters = 96, kernel_size = (3,3),padding = 'Same',activation ='relu'))
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dense(3, activation = "softmax"))

W1016 18:56:33.038396  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1016 18:56:33.062397  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1016 18:56:33.066398  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1016 18:56:33.092399  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.p

In [8]:
model.compile(optimizer=Adam(lr=0.001),loss='categorical_crossentropy',metrics=['accuracy'])

W1016 18:56:33.268409  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1016 18:56:33.279410  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:3576: The name tf.log is deprecated. Please use tf.math.log instead.



In [9]:
model.fit(x_train,y_train,epochs=20, validation_data=(x_test,y_test))

W1016 18:56:33.757437  2372 deprecation.py:323] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W1016 18:56:33.847442  2372 deprecation_wrapper.py:119] From c:\users\tanishqa mahendru\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Train on 109 samples, validate on 37 samples
Epoch 1/20
109/109 [==============================] - ETA: 5s - loss: 1.1134 - acc: 0.406 - ETA: 2s - loss: 1.5542 - acc: 0.359 - ETA: 0s - loss: 1.4148 - acc: 0.385 - 7s 63ms/step - loss: 1.3794 - acc: 0.3761 - val_loss: 1.0877 - val_acc: 0.4324
Epoch 2/20
109/109 [==============================] - ETA: 3s - loss: 1.0843 - acc: 0.468 - ETA: 2s - loss: 1.1023 - acc: 0.390 - ETA: 0s - loss: 1.0963 - acc: 0.354 - 6s 56ms/step - loss: 1.0937 - acc: 0.3578 - val_loss: 1.1501 - val_acc: 0.2973
Epoch 3/20
109/109 [==============================] - ETA: 3s - loss: 1.0539 - acc: 0.500 - ETA: 2s - loss: 1.0930 - acc: 0.390 - ETA: 0s - loss: 1.0731 - acc: 0.427 - 6s 56ms/step - loss: 1.0758 - acc: 0.4128 - val_loss: 1.0747 - val_acc: 0.2973
Epoch 4/20
109/109 [==============================] - ETA: 3s - loss: 1.0532 - acc: 0.375 - ETA: 2s - loss: 1.0535 - acc: 0.453 - ETA: 0s - loss: 1.0425 - acc: 0.489 - 6s 57ms/step - loss: 1.0313 - acc: 0.4954 - va

import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow import lite

from keras.models import load_model
model.save("li.h5")

converter = lite.TocoConverter.from_keras_model_file(keras_file)
tflite_model = converter.convert()
open("lin.tflite", "wb").write(tflite_model)

In [11]:
pred=model.predict(x_test)
print(pred)

[[1.6750904e-03 1.4675467e-02 9.8364949e-01]
 [6.5605063e-04 4.8157653e-01 5.1776737e-01]
 [7.0031613e-01 2.5625378e-01 4.3430094e-02]
 [7.3005613e-03 3.7982516e-02 9.5471692e-01]
 [8.7908667e-01 3.2872006e-02 8.8041395e-02]
 [1.3497718e-02 8.0366832e-01 1.8283390e-01]
 [1.9464317e-01 1.4902729e-01 6.5632957e-01]
 [1.1180455e-01 6.0195172e-01 2.8624374e-01]
 [4.3517012e-02 4.5706096e-01 4.9942201e-01]
 [4.4974485e-01 5.4536104e-01 4.8941332e-03]
 [7.3949224e-01 6.9948114e-02 1.9055966e-01]
 [3.0428341e-01 4.9265072e-01 2.0306598e-01]
 [1.6224814e-03 7.3050672e-01 2.6787084e-01]
 [1.3205211e-01 1.4454457e-01 7.2340333e-01]
 [2.1522641e-02 8.4265196e-01 1.3582535e-01]
 [6.7517656e-01 2.0529570e-01 1.1952775e-01]
 [1.8854941e-01 4.4715634e-01 3.6429426e-01]
 [8.6109234e-05 9.9803728e-01 1.8766223e-03]
 [8.9285153e-01 9.8397680e-02 8.7507665e-03]
 [1.6750904e-03 1.4675467e-02 9.8364949e-01]
 [4.3772709e-02 9.0741557e-01 4.8811719e-02]
 [3.4888905e-02 9.4220346e-01 2.2907637e-02]
 [1.824347

In [12]:
pred_digits=np.argmax(pred,axis=1)
print(pred_digits)

[2 2 0 2 0 1 2 1 2 1 0 1 1 2 1 0 1 1 0 2 1 1 2 1 0 2 2 0 2 0 2 1 0 2 0 0 1]


In [13]:
print(y_test[0])

[0. 0. 1.]


In [14]:
print(y_test[1])

[0. 0. 1.]


In [15]:
print(y_test[2])
print(y_test[3])
print(y_test[4])
print(y_test[5])

[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[0. 1. 0.]


In [120]:
import numpy as np
from PIL import Image

In [121]:
#img = np.invert(Image.open("C:\\Users\\Tanishqa Mahendru\\Desktop\\proj\\dataset\\ab.12.jpg").convert('L')).ravel()
img = Image.open("C:\\Users\\Tanishqa Mahendru\\Desktop\\proj\\dataset\\bu.16.jpg")

In [122]:
imgarr= np.array(img)

In [123]:
imgarr.resize(1,150,150,3)

In [124]:
pred1=model.predict(imgarr)

In [125]:
print(pred1)
print(np.argmax(pred1))

[[0. 0. 1.]]
2


In [126]:
X[0].shape

(150, 150, 3)